apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
#          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              value: your-mongo-username
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              value: your-mongo-password
#          resources:
#            requests:
#              memory: "512Mi" # Adjust memory and CPU requests based on your requirements
#            limits:
#              memory: "1Gi"   # Adjust memory and CPU limits based on your requirements

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb # This selector should match the labels in your MongoDB Deployment
  ports:
    - protocol: TCP
      port: 27017  # Port on which MongoDB is running inside the pods
      targetPort : 27017
  type: ClusterIP # Use ClusterIP for internal cluster access